# Generated by Django 4.2 on 2025-12-24 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(max_length=200)),
                ('population_size', models.IntegerField(default=50)),
                ('mutation_rate', models.FloatField(default=0.1)),
                ('crossover_rate', models.FloatField(default=0.8)),
                ('num_generations', models.IntegerField(default=100)),
                ('bilstm_units', models.IntegerField(default=128)),
                ('dropout_rate', models.FloatField(default=0.3)),
                ('learning_rate', models.FloatField(default=0.001)),
                ('batch_size', models.IntegerField(default=32)),
                ('epochs', models.IntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('upload', 'Image Upload'), ('prediction', 'Model Prediction'), ('training', 'Model Training'), ('error', 'System Error'), ('user_action', 'User Action')], max_length=20)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModelPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_version', models.CharField(max_length=50)),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('auc_score', models.FloatField()),
                ('training_date', models.DateTimeField(auto_now_add=True)),
                ('configuration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.modelconfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('total_images', models.IntegerField(default=0)),
                ('stroke_images', models.IntegerField(default=0)),
                ('non_stroke_images', models.IntegerField(default=0)),
                ('file_path', models.CharField(max_length=500)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
