# Generated by ChatGPT - add history field to ModelPerformance
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_modelperformance_dataset_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelperformance',
            name='history',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
