# Generated by Django 4.2 on 2025-12-24 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CTScanImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=100)),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_age', models.IntegerField()),
                ('patient_gender', models.CharField(max_length=10)),
                ('original_image', models.ImageField(upload_to='ct_scans/original/')),
                ('preprocessed_image', models.ImageField(blank=True, null=True, upload_to='ct_scans/preprocessed/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StrokeDetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.CharField(max_length=20)),
                ('confidence_score', models.FloatField()),
                ('processing_time', models.FloatField()),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.CharField(default='v1.0', max_length=50)),
                ('ct_scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='detection.ctscanimage')),
            ],
        ),
    ]
